---

- hosts: localhost
  tasks:
    - name: install packages_to_install
      become: yes
      package:
        name: "{{ item }}"
        state: present
        # TODO:
        # fireshot
        # google-chrome
        # spotify
        # hub
        with_items:
          - arandr
          - bluez
          - bluez-tools
          - curl
          - fasd
          - git
          - htop
          - inotify-tools
          - shellcheck
          - tmux
          - tree
          - vim
          - wget
          - xclip
  roles:
    - { role: 'diff_so_fancy', tags: 'diff_so_fancy' }
    - { role: 'fzf', tags: 'fzf' }
    - { role: 'golang', tags: 'golang' }
    - { role: 'hub', tags: 'hub' }
    - { role: 'jupyter', tags: 'jupyter' }
