- name: install packages_to_install
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_to_install }}"

- name: install diff-so-fancy into /usr/local/bin
  become: yes
  copy:
    src: diff-so-fancy
    dest: /usr/local/bin/diff-so-fancy
    mode: 0755
    owner: root

- name: set fact to install snaps
  set_fact:
    install_snaps: true

- name: install snaps_to_install
  become: yes
  snap:
    name: "{{ item.snap }}"
    classic: "{{ item.classic | default('no') }}"
    state: present
  with_items: "{{ snaps_to_install }}"
  when: install_snaps

- name: install fzf
  block:
  - name: clone junegunn/fzf
    git:
      repo: https://github.com/junegunn/fzf.git
      dest: "{{ lookup('env','HOME')  }}/.fzf"

  - name: run install script
    command: "bash {{ lookup('env','HOME')  }}/.fzf/install"
