#!/usr/bin/env bash
#
# Runs a specified playbook or all playbooks defined in computer.yml.
#
# Usage:
#
# ./script/setup

echo "+ prompting for user sudo password to be used with ansible..."
ansible-playbook computer.yml --ask-become-pass
