#!/bin/bash

source "$HOME/.files/lib/environment"

link_safe() {
  SOURCE_PATH=$1

  DEFAULT_DESTINATION=$HOME/$(basename $SOURCE_PATH)
  DESTINATION_PATH=${2:-$DEFAULT_DESTINATION}

  # A file/dir doesn't already exist or is a symlink that needs an updated path
  if [ ! -e "$DESTINATION_PATH" ] || [[ -L "$DESTINATION_PATH" && "$(readlink "$DESTINATION_PATH")" != "$SOURCE_PATH" ]]; then
    echo "Linking $DESTINATION_PATH to $SOURCE_PATH"
    rm -f "$DESTINATION_PATH"
    ln -s "$SOURCE_PATH" "$DESTINATION_PATH"
  else
    echo "(Already Exists) Skipping: $DESTINATION_PATH"
  fi
}

# Links all dotfiles in root directory that are not in .symlinkignore
link_dotfiles() {
  for file in $(find $DOTFILES_ROOT -name ".[^.]*" -maxdepth 1); do
    filename=$(basename "$file")
    grep_result=$(grep -w $filename $DOTFILES_ROOT/.symlinkignore)

    if [ ! $grep_result &> /dev/null ]; then
      link_safe $file
    fi
  done
}


link_dotfiles
