#!/usr/bin/env bash

set -e

verify() {
  pkg="$1"
  echo -ne "$pkg: "
  type "$pkg" >/dev/null
  echo -ne "OK\n"
}


commands=(
blueman-manager
curl
fasd
htop
inotifywait
shellcheck
tmux
tree
vim
wget
)
for cmd in "${commands[@]}"; do
  verify "$cmd"
done

echo "--------------------------------------------"
echo "ALL TESTS PASSED."
