#!/usr/bin/env bash

set -e

verify() {
  pkg="$1"
  echo -ne "$pkg: "
  type "$pkg" >/dev/null
  echo -ne "OK\n"
}


commands=(
arandr
bluetoothctl
curl
fasd
fzf
git
htop
hub
inotifywait
shellcheck
tmux
tree
vim
wget
xclip
)
for cmd in "${commands[@]}"; do
  verify "$cmd"
done

echo "--------------------------------------------"
echo "ALL TESTS PASSED."
